# Generated by Django 2.2 on 2022-01-30 16:11

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_admin', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default='2022-01-30 16:11:43')),
                ('updated_at', models.DateTimeField(null=True)),
                ('date_joined', models.DateTimeField(default='2022-01-30 16:11:43')),
                ('email', models.CharField(default=0, max_length=255)),
                ('first_name', models.CharField(default=0, max_length=30)),
                ('is_active', models.IntegerField(default=0)),
                ('is_staff', models.IntegerField(default=0)),
                ('is_superuser', models.IntegerField(default=0)),
                ('last_login', models.DateTimeField(default='2022-01-30 16:11:43')),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
