# Generated by Django 2.2 on 2021-12-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_club', '0002_mychunkedupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='mous',
            name='mou_date',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
